const announcements = [
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Գեղարքունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Գեղարքունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Լոռի',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Լոռի',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Սյունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Սյունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Սյունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Արարատ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Լոռի',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Լոռի',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Արագածոտն',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Արագածոտն',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Արագածոտն',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Կոտայք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Կոտայք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Լոռի',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Սյունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Սյունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Տավուշ',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Արմավիր',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Արմավիր',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Փոխանակում',
        'location':'Գեղարքունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Գեղարքունիք',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
    {
        'header':'',
        'description':'',
        'photoLink':'',
        'status':'Վաճառք',
        'location':'Երեւան',
        'publicationDate':'12.09.2019',
        'lastUpdated':'Մարտ 05, 2021 17:34',
        'sellerName':'Աշոտ',
        'sellerPhotoLink': 'https://bit.ly/3eryxp1',
        'category':'',
    },
]

